# Generated by Django 2.0.5 on 2018-05-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180520_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='like',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
    ]
